id: P000700
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00KG07619
  title: སྐྱེ་བ་སྔ་ཕྱིའི་རྣམ་གཞག་དང་ལུགས་གཉིས་གསལ་བའི་མེ་ལོང་
  author: ''
  volumes:
    1fad0d5a32a7475c88a6d7a9a39d02b4:
      image_group_id: I00KG08423
      title: ''
      volume_number: 1
      total_pages: 418
      base_file: v001.txt
